#!/bin/sh

HOMEBREW_PREFIX="/opt/homebrew"

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

update_shell() {
  local shell_path;
  shell_path="$(command -v fish)"

  fancy_echo "Changing your shell to fish ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."

  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/ope/homebrew/bin/brew shellenv)"' >> "$HOME/.zprofile"
  eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "universal-ctags/universal-ctags"

# Unix
brew "universal-ctags", args: ["HEAD"]
cask "alacritty"
brew "bat"
brew "exa"
brew "fd"
brew "fish"
brew "git"
brew "neovim"
brew "procs"
brew "ripgrep"
brew "starship"
brew "tokei"

# GitHub
brew "gh"

# Programming language prerequisites and package managers
brew "asdf"

# Other basic 3rd-party tools
cask "1password"
cask "1password-cli"
cask "aerial"
cask "backblaze"
cask "docker"
cask "transmit"
mas "Amphetamine", id: 937984704
mas "DuckDuckGo Privacy Essentials", id: 1_482_920_575
mas "Kindle", id: 405_399_194
mas "Magnet", id: 441_258_766
mas "Slack", id: 803_453_959
EOF

if ! command -v heroku >/dev/null; then
  # As of 2021-08-04, no Homebrew bottle for Apple Silicon
  fancy_echo "Installing Heroku CLI ..."

  curl https://cli-assets.heroku.com/install.sh | sh
fi

case "$SHELL" in
  */fish)
    if [ "$(command -v fish)" != "$HOMEBREW_PREFIX/bin/zsh" ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac
